version: '3.3'

services:
  db:
    container_name: db
    build: database/.
    # image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # restart: always