version: '3.3'

services:
  db:
    container_name: db
    build: ./database
    restart: always
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
      - "5432:5432"