services:
  subscriptions.api:
    image: subscriptions.api
    build:
      context: .
      dockerfile: Subscriptions/Subscriptions.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
